spring.application.name=live-scores
server.port=8099
management.endpoints.web.exposure.include=health,info,metrics
apifootball.base-url=https://v3.football.api-sports.io
apifootball.key=${APIFOOTBALL_KEY:81c9d306d8d84c8c22cbd42a154a996a}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
apifootball.quota-per-day=7500
spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL:http://ollama:11434}
spring.ai.ollama.chat.options.model=mistral
# Optionnel: filtrer par compétitions (ids séparés par virgules)
# Tunisia: Ligue I=42, Ligue 2=343, Cup=427 (ex)
apifootball.competition-ids=2,3,39,61,78,88,94,135,140,203,253
#apifootball.competition-ids=2,5,97,162,163,160,167,169,77,179,178,182,333,334,227,244,42,343,427,19,223,245,446,224,243,242,1,4,38,36,35,313,305,287,281
app.ai.timeout-seconds=${APP_AI_TIMEOUT_SECONDS:8}
app.ai.max-concurrent-requests=${APP_AI_MAX_CONCURRENT_REQUESTS:1}
